language: java
jdk:
- oraclejdk8
branches:
  only:
  - development
notifications:
  email:
    recipients:
    - martin.oconnor@stanford.edu
    on_success: never
    on_failure: always
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy --settings .m2/travis-settings.xml'
env:
  global:
  - secure: LNpfgqqfdoqi+1w/Z0uM2D2kJROCZL5u6ZE8iVYWyxeSLjkVG0IqKTPAh3O8jSKQSGOjRpFkeuE6T0Bf5YwaZuyPFvESJTTEKbOP3odc7uqQG67xF+atRWeNsTge7h4/rJMkCmJkI9AhQ1SLDiUMRrR5qMp2aBTlb1enKiH+h4/Oa3nJzyAvRFfl9uxekKr7MCCOcMfF2k6BFkeIADixERTFPlzM1vSWUKdaD0Cst7LJO3tQtMbWk11SXzytyv5mE747qdz21owO+6wFnEET3yvtX6CdQ2103N9uKOav7phsmM9nYazY03Ll7KLFdiMwHN5gtuuX9OAcMA8GGZJMYyVOZYWWnfVDy9qW8Id8vbSX4eGmGAV5T/WP5VaqzZRfPoi9+yORCM1mP67QLCK+fxhveLvS+W6wys6ESDJyg97H3XqGeppDeKk0t4qgTJqUouaZdOWXAsO8TW81fSDkAmSCVtKls4vpbsbrXNRQcaWdZocc2QRGzoUks+qM3faGNUaEfXMgGprwD+VXBb2h6syzpSQU2q9uG4XMbYUgc6oTsYiJ9YUX4rwFdaUc/irKhGEreiPmXPwTFeDTvc8Qp4lKDVHjGgy8wtkn+pAocddzLbHSZpH3tJeE+hoykgICrmnuLr9IQyjuVkSbHs/KKrxF/RD3mXqx/JC9w+gTUrY=
  - secure: My12qm0fX8k422rux7ExIZlVmsj/Ehh9DUmOQnPshA1Ob2z6ntHxsAl45GLdb74qUXuUNzqWCJfw04svcppEzM3WZGQ3S3/c1d0xYxwMMe68ioXpvu5t5PhmxYXeWJxDI2h1MW3iLwWARge6ho72ax3aVZh+LFXn0DOcIcL2kXbk1XSxNX5SyP49AGe8uhJihTyhssXZ07jUcIjMTpY8fABcZBjZHDMQsV5NlSDWlxdbSex/0aG2ucdCk8CpgLSCe//O/89pBs3t7WjUMvXptfWty35ey5DuCSqnYEPXCSHPTsNCFgKTAU6h9mWJ7QTvKBAL3lNTJ6ZyqU9yKSYQgCq2V/zup36z+OtxKsir/WS7qPkUomSfY7JOJ8AUYkO+sZCIzxVKF1hlCnQIq2aZkay5Lg+NyxhWmnmjgparaNUoY6O9gq55RXf82Apz/vsWKfuR/HzD2o60b3DEtJd/SHjj3iziKlBPFc1aoTlqVXdt+t0aTekdA6V7Y1QLXy/rUIrS3FflsKEA7shqRrI7LWAISXVsUzdat1FhyUeQGotlBtvqTjYxOIRYZn3u6kU8OnZLrnL8q3aXtc905KPD2IgBHlc+xhoPPZ9PyQ+GcXclrThuN9COu9ObMBUVZ/OIwD4TEOqd1MiWz76QC1KcT7reUxibHEj672CwywGZ6Rk=
