language: java
jdk:
- oraclejdk8
branches:
  only:
  - development
notifications:
  email:
    recipients:
    - martin.oconnor@stanford.edu
    on_success: never
    on_failure: always
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy --settings .m2/travis-settings.xml'
env:
  global:
  - secure: nvQ0crmUW0qyTcacVqTUpeBhWZBoYBup2PxP74nis9gavGB+dbihrOuDmPKV6oTmKIc+eRdylPlJK6L4272nS686GUWwGqUmiL4IePR1L7/c/7pDdoKhbaSRCQVvpBO/eOpXEqXgc5ilrsNrPbpywJ8sSYQW0sKSoO+18HY168OLYo6gsmK2TTV3TIFbLaWhWLZYb0Vg8bWXj9ccyMzkfRQkedzU4A569zIsx4GM5CCU0ksZyDEEvKoRsFqUWF9TMHgIYMaFEv4Mq4jmAsPMpq7T1TulK5sAMb+/ynvFQHoqCnfcPIBjdkG2SkBmN4gMjjwYJqL0N6u/uJYuTfaJXx8AAzamfZFyCPvZeiB3KB+4VUJHTk48xRHtVZ058xmeWIkMyfvNiahYFR6fq+nnGqaDoPzoNulMfJj+gm2qPQn9r5NAqJXIuBM8Kb91rngMjUyxWafNQv+aSZDWsCMAVKs8p3PBv/jONAtmAn6BqdVuK1P4HlajHSyb/ePYbbo5LK1RRFGvUDppy46FpIxHKaKBzxL0VAg9L07KJkQBpw1JulWJpr4gpHiwrOHAStPmt97aEzkHZqGs4oujnAuhFQfAB0wlObYrgqkHWMz7Wt/pDTUxWncyDMI2vSt31GpkKL98QOZS22QHanlTs0xvzofCcUnqMz7WyrECOrzUlIc=
  - secure: oHKfVuhOrG6HcjxXnU2yl4IyevO1JA7ZhkfLiM9z+NcbbP6QRz3hzqYKC/xNSizjJo5KkKHF4dhspjuFrZKt0RQSbP6tHN0IXQp5GftaLkisMrTeVn8YJUUkgZbO3s3C49oK2LJILCnOEsDjHfgSiW0mgTU6/2TCyd2gZiI6l8Ve5sqxLgK5uofMMLDpzwR1yN/7D0a5KwlXSUcTKq3/NJlQwajkleGbFfCKxOaZRV05y6PH0wkk4IBHdXDqAnY90JbkEVHQ60adtRv7wVVYpW1iZTslspxWao79HFyifC5XnxgEiQeQRYtsYGKF6yh+YVK34U6FVKWu3CArYxWcaxrJA3KQrtU3IQiXm1qw8lkRL9xERzcVtGj0OtCciIJLeDOtIBYXNr7pwWuIUKQs3Q7KJQ3eTE9vJMzwYvaI9pOaoCbFli5ceE879E48m0ngTaC4YEZ4Eeq44sHg8xjnZqpaRCbn8Q6cbF1cBH2KliDYV82xTpgJxJ2PU0qRX1Mtw4HmlrLjvpbDQXWkHTPFXlOODmLkLJwYFqfUboUckJudXlXoQ7KvwVG4n4sjKP7WoTx2/pqCHKnyKd7tLUio9z5Y/HvSzVL8g+BURHbq2iW9wtBJ92NGCXfvXcUkCE+8tkcWr5qfbvbLR4XWtUlGG3YHSKRJVGzuZ+oYOE2BAnw=
